ALTER TABLE complaint_meetings
ADD COLUMN IF NOT EXISTS minutes TEXT,
ADD COLUMN IF NOT EXISTS conclusion VARCHAR(100),
ADD COLUMN IF NOT EXISTS agreed_containment TEXT,
ADD COLUMN IF NOT EXISTS is_concluded BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS concluded_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS concluded_by VARCHAR(50);
